In [15]:
import cv2

In [ ]:
df=pd.read_csv("automobile.csv",)

In [16]:
img=cv2.imread('20149df0-4f44-4013-b388-2fe858c06a93.jpg',1)

In [3]:
print(img)
print(img.shape)

[[[58 54 53]
  [58 54 53]
  [58 54 53]
  ...
  [58 54 53]
  [58 54 53]
  [58 54 53]]

 [[58 54 53]
  [58 54 53]
  [58 54 53]
  ...
  [58 54 53]
  [58 54 53]
  [58 54 53]]

 [[58 54 53]
  [58 54 53]
  [58 54 53]
  ...
  [58 54 53]
  [58 54 53]
  [58 54 53]]

 ...

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]]
(1200, 540, 3)


In [17]:
cv2.imshow('legend_1',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
resized=cv2.resize(img,(600,600))
cv2.imshow('legend_2',resized)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [19]:
resized_1=cv2.resize(img,(int(img.shape[1]/2),int(img.shape[2]/2)))
cv2.imshow('legend_3',resized_1)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Face detection

In [20]:
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

In [21]:
img_1=cv2.imread('WhatsApp Image 2022-02-13 at 12.25.15 PM.jpeg')

In [22]:
gray_img= cv2.cvtColor(img_1,cv2.COLOR_BGR2GRAY)

In [23]:
faces= face_cascade.detectMultiScale(gray_img, scaleFactor= 1.05, minNeighbors=5)

In [24]:
print(type(faces))
print(faces)

<class 'numpy.ndarray'>
[[394 159 392 392]
 [384  54  90  90]]


In [25]:
for (x, y, w, h) in faces:
    cv2.rectangle(img_1, (x, y), (x+w, y+h), (0,255, 0), 3)
resized= cv2.resize(img_1,(int(img_1.shape[1]),int(img_1.shape[0])))
cv2.imshow('Gray',resized)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
import numpy as np
import cv2

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

img = cv2.imread('test_img')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(gray, 1.3, 5)
#faces = face_cascade.detectMultiScale(gray)

for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv2.imshow('img',img)

k = cv2.waitKey(0)
if k == 27:         # wait for ESC key to exit
    cv2.destroyAllWindows()
elif k == ord('s'): # wait for 's' key to save and exit
    cv2.imwrite('messigray.png',img)
    cv2.destroyAllWindows()