In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('train.csv.zip')

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
###Drop Nan Values
df=df.dropna()

In [5]:
## Get the Independent Features

X=df.drop('label',axis=1)

In [6]:
## Get the Dependent features
y=df['label']

In [7]:
X.shape

(18285, 4)

In [8]:
y.shape

(18285,)

In [9]:
import tensorflow as tf

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [11]:
### Vocabulary size
voc_size=5000

### Onehot Representation

In [12]:
messages=X.copy()

In [13]:
messages['title'][1]

'FLYNN: Hillary Clinton, Big Woman on Campus - Breitbart'

In [14]:
messages.reset_index(inplace=True)

In [15]:
import nltk
import re
from nltk.corpus import stopwords

In [16]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [17]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 

### Embedding Representation

In [19]:
sent_length=20
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 3387  527 1190]
 [   0    0    0 ... 4523   60 4213]
 [   0    0    0 ... 3368 1732 1273]
 ...
 [   0    0    0 ... 4649 2813 3543]
 [   0    0    0 ... 4213  364 3209]
 [   0    0    0 ... 3200  797 3003]]


In [20]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 2682,
       1442, 1982, 3798, 2253,  423, 1910, 3387,  527, 1190])

In [21]:
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Bidirectional(LSTM(100)))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 20, 40)            200000    
                                                                 
 bidirectional (Bidirectiona  (None, 200)              112800    
 l)                                                              
                                                                 
 dense (Dense)               (None, 1)                 201       
                                                                 
Total params: 313,001
Trainable params: 313,001
Non-trainable params: 0
_________________________________________________________________
None


In [22]:
len(embedded_docs),y.shape

(18285, (18285,))

In [23]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [24]:
X_final.shape,y_final.shape

((18285, 20), (18285,))

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.33, random_state=42)

### Model Training

In [26]:
### Finally Training
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10)

Epoch 1/10
383/383 [==============================] - 13s 23ms/step - loss: 0.2609 - accuracy: 0.8806 - val_loss: 0.1962 - val_accuracy: 0.9165
Epoch 2/10
383/383 [==============================] - 8s 20ms/step - loss: 0.1269 - accuracy: 0.9509 - val_loss: 0.2222 - val_accuracy: 0.9175
Epoch 3/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0881 - accuracy: 0.9696 - val_loss: 0.2410 - val_accuracy: 0.9135
Epoch 4/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0563 - accuracy: 0.9819 - val_loss: 0.3354 - val_accuracy: 0.9110
Epoch 5/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0378 - accuracy: 0.9878 - val_loss: 0.3778 - val_accuracy: 0.9075
Epoch 6/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0196 - accuracy: 0.9941 - val_loss: 0.3713 - val_accuracy: 0.9117
Epoch 7/10
383/383 [==============================] - 8s 21ms/step - loss: 0.0121 - accuracy: 0.9963 - val_loss: 0.5021 - val_accuracy: 0.906

In [27]:
X_train.shape

(12250, 20)

In [28]:
X_test.shape

(6035, 20)

In [29]:
y_pred=model.predict(X_test)

189/189 [==============================] - 2s 7ms/step


In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
confusion_matrix(y_test,y_pred)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,y_pred)